	<img id="ContentBoxHeadline" class="Title" src="layouts/tibiacom/images/header/headline-eventshop.png" alt="Contentbox headline">
 
<center><h2><b><font color=red>EVENT SHOP</font></b></h2></center>
<br>
<br>
<table style='width:90%;margin-left:auto;margin-right:auto'><tr bgcolor='#BDB76B'><td colspan='2' style='color:white;font-weight:bold'><center><img src='http://tibiawiki.com.br/images/a/ab/Bar_of_Gold.gif' width=20 height=20/>Como conseguir BAR OF GOLD?<img src='http://tibiawiki.com.br/images/a/ab/Bar_of_Gold.gif' width=20 height=20/></center></td></tr>
<tr bgcolor='#EEE8AA'><td colspan='2' font-weight:bold'>Para conseguir <b>BAR OF GOLD</b> é necessario participar de eventos do servidor ou comprar de outros jogadores, atualmente temos o      <A href='http://aurera-global.com/index.php?subtopic=battlefield'><b>BATTLEFIELD</b></A> e o <A href='http://aurera-global.com/index.php?subtopic=CapturetheFlag'><b>CAPTURE THE FLAG</b></A>, ambos oferece como recompensa a quantidade de <b>10 BAR OF GOLD</b>.</td></tr>
</table><br><br>

<table style='width:90%;margin-left:auto;margin-right:auto'><tr bgcolor='#BDB76B'><td colspan='2' style='color:white;font-weight:bold'><center><img src='http://tibiawiki.com.br/images/7/7b/Map_%28Colour%29.gif' width=20 height=20/>Onde Trocar<img src='http://tibiawiki.com.br/images/7/7b/Map_%28Colour%29.gif' width=20 height=20/></center></td></tr>
<tr bgcolor='#EEE8AA'><td colspan='2' font-weight:bold'>Para trocar suas <b>BARRAS DE OURO</b> por itens, o jogador deve escolher o item desejado na tabela abaixo e em seguida ir até o <b>NPC KATABUM</b> que está localizado no sub solo do <b>TEMPLO DE CARLIN</b>, o npc só aparecerá aos <u>sabados</u> e <u>domingos</u>.</td></tr>
</table><br><br>

<table style='width:90%;margin-left:auto;margin-right:auto'><tr bgcolor='#BDB76B'><td colspan='2' style='color:white;font-weight:bold'><center>Imagem</center></td><td colspan='2' style='color:white;font-weight:bold'><center>Descrição</center></td><td colspan='2' style='color:white;font-weight:bold'><center>Quant.(BOG)</center></td></tr>
<tr bgcolor='#EEE8AA'><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/f/fc/Essence_of_Wishful_Thinking.gif'/></center></td><td colspan='2' font-weight:bold'><b>Small Stamina Refil</b><br>You see small stamina refil. <br>It weighs 0.30 oz. <br>Use to 3 hours regeneration stamina.</td><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/a/ab/Bar_of_Gold.gif'/><br><b>50</center></td></tr>
<tr bgcolor='#EEE8AA'><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/0/05/Zaoan_Chess_Box.gif'/></center></td><td colspan='2' font-weight:bold'><b>Zaoan Chess Box</b><br>(Vol: 32).<br>It weighs 38.00 oz.<br>This chess box is made of jade and obsidian. It will hold a full set of 32 Zaoan chess figures.</td><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/a/ab/Bar_of_Gold.gif'/><br><b>100</b></center></td></tr>
<tr bgcolor='#EEE8AA'><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/0/03/Pannier_Backpack.gif'/></center></td><td colspan='2' font-weight:bold'><b>Pannier Backpack</b><br>(Vol: 20).<br>It weighs 18.00 oz.</td><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/a/ab/Bar_of_Gold.gif'/><br><b>70</center></td></tr>
<tr bgcolor='#EEE8AA'><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/d/d0/Green_Light.gif'/></center></td><td colspan='2' font-weight:bold'><b>Green Light</b><br>It weighs 0.20 oz.</td><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/a/ab/Bar_of_Gold.gif'/><br><b>70</b></center></td></tr>
<tr bgcolor='#EEE8AA'><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/d/d9/Blood_Herb.gif'/></center></td><td colspan='2' font-weight:bold'><b>03 Blood Herb</b><br>It weighs 3.60 oz.</td><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/a/ab/Bar_of_Gold.gif'/><br><b>10</b></center></td></tr>
<tr bgcolor='#EEE8AA'><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/5/5c/Draken_Doll.gif'/></center></td><td colspan='2' font-weight:bold'><b>Draken doll</b><br>It weighs 15.00 oz.<br>This doll seems to be the favourite doll of the emperor. It was rewarded by TibiaJourney.com.</td><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/a/ab/Bar_of_Gold.gif'/><br><b>70</b></center></td></tr>
<tr bgcolor='#EEE8AA'><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/a/a7/Bear_Doll.gif'/></center></td><td colspan='2' font-weight:bold'><b>Bear doll</b><br>It weighs 5.90 oz.</td><td colspan='2' font-weight:bold'><center><img src='http://tibiawiki.com.br/images/a/ab/Bar_of_Gold.gif'/><br><b>70</b></center></td></tr>
</table>